on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Zip directories
        run: |
          mkdir output
          zip -r output/firefox.xpi ${{ github.workspace }}/firefox/*
          zip -r output/chrome.crx  ${{ github.workspace }}/chrome/*
          ls -l output
      - name: Upload archives
        uses: actions/upload-artifact@v3
        with:
          name: extensions
          path: |
            '${{ github.workspace }}/output/*'
