on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Zip directories
        run: |
          zip -r firefox.xpi firefox
          zip -r chrome.crx chrome
      - name: Upload archives
        uses: actions/upload-artifact@v3
        with:
          name: extensions
          path: |
            '${{ github.workspace }}/*.xpi'
            '${{ github.workspace }}/*.crx'
