on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Zip directories
        run: |
          mkdir output
          zip -r output/firefox.zip ${{ github.workspace }}/firefox/*
          zip -r output/chrome.zip  ${{ github.workspace }}/chrome/*
          pwd
          ls -l
      - name: Upload archives
        uses: actions/upload-artifact@v3
        with:
          name: extensions
          path: |
            '${{ github.workspace }}/*.zip'
